export const history = [
  { id: 1, image: require('@/assets/images/history1.png'), name: "enjoy", title: "socialy buzzed" },
  { id: 2, image: require('@/assets/images/history2.png'), name: "workflow", title: "git commit push" },
  { id: 3, image: require('@/assets/images/history3.png'), name: "react_dev", title: "hooks mastery" },
  { id: 4, image: require('@/assets/images/history4.png'), name: "node_pro", title: "express middleware" },
  { id: 5, image: require('@/assets/images/history5.png'), name: "db_admin", title: "mongodb indexing" },
  { id: 6, image: require('@/assets/images/history6.png'), name: "stylist", title: "tailwind utility" },
  { id: 7, image: require('@/assets/images/history7.png'), name: "pixel", title: "ui design trends" },
  { id: 8, image: require('@/assets/images/history8.png'), name: "backend", title: "restful api logic" },
  { id: 9, image: require('@/assets/images/history9.png'), name: "frontend", title: "nextjs server components" },
  { id: 10, image: require('@/assets/images/history10.png'), name: "coder", title: "javascript algorithms" },
  { id: 11, image: require('@/assets/images/history11.png'), name: "mountain", title: "peak performance" },
  { id: 12, image: require('@/assets/images/history12.png'), name: "ocean", title: "deep blue waves" },
  { id: 13, image: require('@/assets/images/history13.png'), name: "urban", title: "city lights" },
  { id: 14, image: require('@/assets/images/history14.png'), name: "forest", title: "green sanctuary" },
  { id: 15, image: require('@/assets/images/history15.png'), name: "desert", title: "golden dunes" },
  { id: 16, image: require('@/assets/images/history16.png'), name: "space", title: "galactic voyage" },
  { id: 17, image: require('@/assets/images/history17.png'), name: "retro", title: "vintage vibes" },
  { id: 18, image: require('@/assets/images/history18.png'), name: "future", title: "cyberpunk city" },
  { id: 19, image: require('@/assets/images/history19.png'), name: "minimal", title: "clean aesthetic" },
  { id: 20, image: require('@/assets/images/history20.png'), name: "vibrant", title: "color explosion" },
  { id: 21, image: require('@/assets/images/history21.png'), name: "coffee", title: "morning ritual" },
  { id: 22, image: require('@/assets/images/history22.png'), name: "travel", title: "wanderlust dreams" },
  { id: 23, image: require('@/assets/images/history23.png'), name: "gym", title: "iron paradise" },
  { id: 24, image: require('@/assets/images/history24.png'), name: "yoga", title: "inner peace" },
  { id: 25, image: require('@/assets/images/history25.png'), name: "gaming", title: "level up" },
  { id: 26, image: require('@/assets/images/history26.png'), name: "music", title: "rhythm of life" },
  { id: 27, image: require('@/assets/images/history27.png'), name: "books", title: "story teller" },
  { id: 28, image: require('@/assets/images/history28.png'), name: "art", title: "creative canvas" },
  { id: 29, image: require('@/assets/images/history29.png'), name: "cooking", title: "culinary arts" },
  { id: 30, image: require('@/assets/images/history30.png'), name: "crypto", title: "blockchain tech" },
  { id: 31, image: require('@/assets/images/history31.png'), name: "startup", title: "hustle hard" },
  { id: 32, image: require('@/assets/images/history32.png'), name: "mentor", title: "guiding light" },
  { id: 33, image: require('@/assets/images/history33.png'), name: "student", title: "learning phase" },
  { id: 34, image: require('@/assets/images/history34.png'), name: "pilot", title: "high altitude" },
  { id: 35, image: require('@/assets/images/history35.png'), name: "driver", title: "open road" },
  { id: 36, image: require('@/assets/images/history36.png'), name: "chef", title: "gourmet flavors" },
  { id: 37, image: require('@/assets/images/history37.png'), name: "doctor", title: "healing hands" },
  { id: 38, image: require('@/assets/images/history38.png'), name: "engineer", title: "building blocks" },
  { id: 39, image: require('@/assets/images/history39.png'), name: "athlete", title: "fast track" },
  { id: 40, image: require('@/assets/images/history40.png'), name: "writer", title: "ink and paper" },
  { id: 41, image: require('@/assets/images/history41.png'), name: "photog", title: "shutter speed" },
  { id: 42, image: require('@/assets/images/history42.png'), name: "cyclist", title: "pedal power" },
  { id: 43, image: require('@/assets/images/history43.png'), name: "skater", title: "halfpipe flow" },
  { id: 44, image: require('@/assets/images/history44.png'), name: "gamer", title: "final boss" },
  { id: 45, image: require('@/assets/images/history45.png'), name: "streamer", title: "live audience" },
  { id: 46, image: require('@/assets/images/history46.png'), name: "podcaster", title: "on the mic" },
  { id: 47, image: require('@/assets/images/history47.png'), name: "blogger", title: "daily update" },
  { id: 48, image: require('@/assets/images/history48.png'), name: "vlogger", title: "frame by frame" },
  { id: 49, image: require('@/assets/images/history49.png'), name: "analyst", title: "data driven" },
  { id: 50, image: require('@/assets/images/history50.png'), name: "founder", title: "visionary path" }
];
