export type History = {
  id: number;
  name: string;
  title: string;
};

export const history: History[] = [
  { id: 1, name: "enjoy", title: "socialy buzzed" },
  { id: 2, name: "workflow", title: "git commit push" },
  { id: 3, name: "react_dev", title: "hooks mastery" },
  { id: 4, name: "node_pro", title: "express middleware" },
  { id: 5, name: "db_admin", title: "mongodb indexing" },
  { id: 6, name: "stylist", title: "tailwind utility" },
  { id: 7, name: "pixel", title: "ui design trends" },
  { id: 8, name: "backend", title: "restful api logic" },
  { id: 9, name: "frontend", title: "nextjs server components" },
  { id: 10, name: "coder", title: "javascript algorithms" },
  { id: 11, name: "mountain", title: "peak performance" },
  { id: 12, name: "ocean", title: "deep blue waves" },
  { id: 13, name: "urban", title: "city lights" },
  { id: 14, name: "forest", title: "green sanctuary" },
  { id: 15, name: "desert", title: "golden dunes" },
  { id: 16, name: "space", title: "galactic voyage" },
  { id: 17, name: "retro", title: "vintage vibes" },
  { id: 18, name: "future", title: "cyberpunk city" },
  { id: 19, name: "minimal", title: "clean aesthetic" },
  { id: 20, name: "vibrant", title: "color explosion" },
  { id: 21, name: "coffee", title: "morning ritual" },
  { id: 22, name: "travel", title: "wanderlust dreams" },
  { id: 23, name: "gym", title: "iron paradise" },
  { id: 24, name: "yoga", title: "inner peace" },
  { id: 25, name: "gaming", title: "level up" },
  { id: 26, name: "music", title: "rhythm of life" },
  { id: 27, name: "books", title: "story teller" },
  { id: 28, name: "art", title: "creative canvas" },
  { id: 29, name: "cooking", title: "culinary arts" },
  { id: 30, name: "crypto", title: "blockchain tech" },
  { id: 31, name: "startup", title: "hustle hard" },
  { id: 32, name: "mentor", title: "guiding light" },
  { id: 33, name: "student", title: "learning phase" },
  { id: 34, name: "pilot", title: "high altitude" },
  { id: 35, name: "driver", title: "open road" },
  { id: 36, name: "chef", title: "gourmet flavors" },
  { id: 37, name: "doctor", title: "healing hands" },
  { id: 38, name: "engineer", title: "building blocks" },
  { id: 39, name: "athlete", title: "fast track" },
  { id: 40, name: "writer", title: "ink and paper" },
  { id: 41, name: "photog", title: "shutter speed" },
  { id: 42, name: "cyclist", title: "pedal power" },
  { id: 43, name: "skater", title: "halfpipe flow" },
  { id: 44, name: "gamer", title: "final boss" },
  { id: 45, name: "streamer", title: "live audience" },
  { id: 46, name: "podcaster", title: "on the mic" },
  { id: 47, name: "blogger", title: "daily update" },
  { id: 48, name: "vlogger", title: "frame by frame" },
  { id: 49, name: "analyst", title: "data driven" },
  { id: 50, name: "founder", title: "visionary path" },
];
